### ISSUE TITLE
Test Improvement Ideas

### ISSUE THREAD

**Issue by haydenbr** [dg92/Performance-Analysis-JS#11]
Just a couple thoughts to improve the tests if you're still working on this.

1) commit the seed data. Probably doesn't make a huge difference, but it would ensure that every run of the test was using the exact same randomly generating data. (On a similar thought, I wonder what would happen if all your test data was zeroes)
2) It would be a little more interesting if you ran each method on each data set size multiple times
3) If you ran every single test run in a brand new Docker container, it would probably get you a little more consistency. It would take a lot more effort and may not be worth, but it would be interesting.

I might pitch in and try my hand at one or all of these. Regardless of the results, it's an interesting idea you had to think to test these things.

**Comment by dg92** [comment]
@haydenbr, thanks for the suggestion, I have started looking into the repo again, will keep you updated, if you have done the above by yourself then MR is welcomed.
