### ISSUE TITLE
invalid numbers 

### ISSUE THREAD

**Issue by ledbit** [dg92/Performance-Analysis-JS#3]
These perf numbers are invalid as you're *NOT* measuring the same thing - for example, according to the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map):

>The map() method creates a **new array with the results** of calling a provided function on every element in the calling array.

The for loop [code ](https://github.com/dg92/Performance-analysis-es6/blob/master/formulas.js#L63-L67) doesn't do the same thing as map would:
```
    console.time('for loop');
    for(let i=0; i<posts.length; i++) {
        posts[i].upvotes = (+posts[i].upvotes + +posts[i].commentCount)/divider;
    }
    console.timeEnd('for loop');
```

Sure, you can say that you're using all these functions just to iterate over an array, but that would clearly be a misuse of the APIs

`find()` has other issues - your for loop implementation returns the **last** element as supposed to the first one from [Array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

When doing perf analysis it is **really important** for the code alternative to do the **same thing,** otherwise the comparison is pointless

**Comment by Dragas** [comment]
I agree.

Also you show a red line in your data results. What does the red line mean? In some cases it corresponds to lowest values, while in some cases it corresponds to greatest values in that column.

**Comment by dg92** [comment]
@ledbit fixed [here](https://github.com/dg92/Performance-analysis-es6/commit/36eba2639d5cd233906a0b2573b343b3512a5a6b) the issue of invalid numbers.
In our case of find, we are finding an object whose id is generated from a random function so, we will have only one element as a result so there is no case of the first or last element.


@Dragas the red line is just for reference, I will update the result soon.
I am working to take into consideration inline caching, cold cache, hidden classes, deoptimizations, garbage collection, JIT, etc.
