### ISSUE TITLE
Why the double + signs?

### ISSUE THREAD

**Issue by stmcallister** [dg92/Performance-Analysis-JS#7]
This is more of a question than an issue. I'm noticing that there are + signs than I'm used to, and I'm wondering what the purpose is. For example, on the reduce section, the equation looks like

`(+posts[i].upvotes + +posts[i].downvotes + +posts[i].commentCount)`

with + symbols before each element and then additional ones in between. I've tested with 

`(posts[i].upvotes + posts[i].downvotes + posts[i].commentCount)`

and it seems to work. Is there something that the additional symbols are doing?

**Comment by dg92** [comment]
@stmcallister they are for implicit conversion to numbers if the modification to data.js is done and let say the number is stored as a string so this will still work.

To better help, let take a case where '1' + '1' will return you 11 whereas +'1'+ +'1' will give your 2 as the +'1' turn to 1 and then the addition take place.

Let me know if you need more clarity.

**Comment by stmcallister** [comment]
@dg92 Ah, I'm glad I asked. I didn't know you could do it that way. Thanks for explaining! I love learning new stuff.
