### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by imranjaved728** [dg92/Performance-Analysis-JS#8]
Hey const {
    map,
    reduce,
    filter,
    find,
    random
} = require('lodash');

Is this syntax pulling specific methods from a library ?? ( map, reduce, filter, find and random) are pulled from lodash here right ?

**Comment by dg92** [comment]
@imranjaved728 yes. you can read about es6 destructuring [here](http://exploringjs.com/es6/ch_destructuring.html)
